tasks:
   - before: yarn --force
     init: yarn --force
     name: Server

   - name: Client
     init: cd client && yarn --force
     before: yarn --force
ports:
   - port: 3000
     visibility: public
     onOpen: ignore
