tasks:
   - init: yarn install --check-files --force
     before: yarn install --check-files --force
     name: Server

   - name: Client
     init: cd client && yarn install --check-files --force
     before: yarn install --check-files --force
ports:
   - port: 3000-7800
     visibility: public
     onOpen: ignore
