tasks:
   - command: |
        yarn
        yarn start:dev
     name: Server
   - command: tsc -w
     name: Typescript
   - name: Client
     command: |
        cd client
        yarn
        yarn start
ports:
   - port: 3000
     visibility: public
     onOpen: ignore
   - port: 7800
     visibility: public
     onOpen: ignore
