tasks:
   - command: yarn
     name: Server

   - name: Client
     command: cd client && yarn
ports:
   - port: 3000
     visibility: public
     onOpen: ignore
   - port: 7800
     visibility: public
     onOpen: ignore
