tasks:
   - init: npm i
     name: Server

   - name: Client
     init: cd client && npm i
ports:
   - port: 3000
     visibility: public
     onOpen: ignore
   - port: 7800
     visibility: public
     onOpen: ignore
