tasks:
   - command: npm i
     name: Server

   - name: Client
     command: cd client && npm i
ports:
   - port: 3000
     visibility: public
     onOpen: ignore
   - port: 7800
     visibility: public
     onOpen: ignore
