tasks:
   - init: npm i
     before: npm i
     name: Server

   - name: Client
     before: cd client && npm i
     init: npm i
ports:
   - port: 3000
     visibility: public
     onOpen: ignore
   - port: 7800
     visibility: public
     onOpen: ignore
