tasks:
   - before: yarn
     init: yarn
     name: Server

   - name: Client
     init: cd client && yarn
     before: cd client && yarn
ports:
   - port: 3000
     visibility: public
     onOpen: ignore
