tasks:
   - init: yarn --check-files --force
     command: yarn
     name: Server

   - name: Backend
     init: cd client && yarn --check-files --force
     before: yarn
ports:
   - port: 3000
     visibility: public
     onOpen: ignore
   - port: 7800
     visibility: public
     onOpen: ignore
